### ISSUE TITLE
Breaks if Ubuntu "gnome-extension-gpaste" package is installed

### ISSUE THREAD

**Issue by eliminmax** [essembeh/gnome-extensions-cli#5]
The Ubuntu package `gnome-extension-gpaste` provides the `GPaste@gnome-shell-extensions.gnome.org` extension, which breaks `gnome-extensions-cli`.

```json
{
    "shell-version": [
        "41", "42"
    ],
    "uuid": "GPaste@gnome-shell-extensions.gnome.org",
    "name": "GPaste",
    "version": "3.42.6",
    "description": "Clipboard management system",
    "url": "http://github.com/Keruspe/GPaste",
    "gettext-domain": "GPaste"
}
```

The error message is as follows:

```
💥 Error: 1 validation error for Metadata
version
  value is not a valid integer (type=type_error.integer)
Traceback (most recent call last):
  File "/home/eliminmax/.local/bin/gext", line 8, in <module>
    sys.exit(run())
  File "/home/eliminmax/.local/pipx/venvs/gnome-extensions-cli/lib/python3.10/site-packages/gnome_extensions_cli/cli.py", line 108, in run
    raise error
  File "/home/eliminmax/.local/pipx/venvs/gnome-extensions-cli/lib/python3.10/site-packages/gnome_extensions_cli/cli.py", line 102, in run
    handler(args, manager, store)
  File "/home/eliminmax/.local/pipx/venvs/gnome-extensions-cli/lib/python3.10/site-packages/gnome_extensions_cli/commands/list_.py", line 40, in run
    extensions = sorted(
  File "/home/eliminmax/.local/pipx/venvs/gnome-extensions-cli/lib/python3.10/site-packages/gnome_extensions_cli/commands/list_.py", line 41, in <lambda>
    manager.list_installed_extensions(), key=lambda x: x.uuid.lower()
  File "/home/eliminmax/.local/pipx/venvs/gnome-extensions-cli/lib/python3.10/site-packages/gnome_extensions_cli/schema.py", line 56, in uuid
    return self.metadata.uuid
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/eliminmax/.local/pipx/venvs/gnome-extensions-cli/lib/python3.10/site-packages/gnome_extensions_cli/schema.py", line 52, in metadata
    return Metadata.parse_file(self.folder / "metadata.json")
  File "pydantic/main.py", line 570, in pydantic.main.BaseModel.parse_file
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Metadata
version
  value is not a valid integer (type=type_error.integer)
```

**Comment by essembeh** [comment]
Hi

I didn't know that extension could be strings, I only encountered integers.

I'll fix it asap.
