### ISSUE TITLE
Errors on fresh install

### ISSUE THREAD

**Issue by OSCrustacean** [essembeh/gnome-extensions-cli#7]
On a fresh install throws error when trying to execute any command:
`Traceback (most recent call last):
  File "/home/oscrustacean/.local/bin/gext", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/oscrustacean/.local/lib/python3.11/site-packages/gnome_extensions_cli/cli.py", line 78, in run
    subparsers.add_parser("update", aliases=["u"], help="update extensions")
  File "/usr/lib64/python3.11/argparse.py", line 1188, in add_parser
    raise ArgumentError(argparse.ArgumentError: argument {list,ls,install,i,uninstall,u,enable,disable,search,show}: conflicting subparser alias: u`

I got this error to go away just by removing the "u" alias on line 78 of cli.py since it is conflicting with something else.

After fixing that, the program throws the error
`File "/home/oscrustacean/.local/bin/gext", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/oscrustacean/.local/lib/python3.11/site-packages/gnome_extensions_cli/cli.py", line 78, in run
    subparsers.add_parser("update", aliases=["u"], help="update extensions")
  File "/usr/lib64/python3.11/argparse.py", line 1188, in add_parser
    raise ArgumentError(
argparse.ArgumentError: argument {list,ls,install,i,uninstall,u,enable,disable,search,show}: conflicting subparser alias: u
[oscrustacean@oscrustacean-pc ~]$ gext list
Traceback (most recent call last):
  File "/home/oscrustacean/.local/bin/gext", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/oscrustacean/.local/lib/python3.11/site-packages/gnome_extensions_cli/cli.py", line 81, in run
    subparsers.add_parser("disable", aliases=[], help="disable extensions")
  File "/usr/lib64/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument {list,ls,install,i,uninstall,u,enable,disable,search,show,update}: conflicting subparser: disable
`
I fixed this simply by commenting out lines 80-83 of cli.py. Is there a reason there are two disable.configure entries?

**Comment by essembeh** [comment]
Thanks for noticing that.

Very strange that I did not get any error ...
I did not use your PR as there were 2 problems, 
- 'u' used twice
- 'disable' was also declared twice
